experiment:
  project: sft_llada_recursive3
  num_node: 1
  logging_dir: sft_llada_recursive3/logs
debug: false
model:
  pretrained_model: GSAI-ML/LLaDA-8B-Base
  optimized_name: optimized_recursive
dataset: gsm8k_aug_nl
training:
  gradient_checkpointing_enable: false
  gradient_accumulation_steps: 4
  batch_size_lm: 16
  mixed_precision: bf16
  enable_tf32: false
  seed: 42
  num_train_epochs: 25
  max_grad_norm: 1
  method: random_masking
  lower_p: 0.1
  upper_p: 0.9
  block_size: 32
  mask_times_per_sample: 1
  post_num: 8
  max_gen_length: 512
  max_prompt_len: 784
  use_latent_recursive: true
  R: 2
  recursive_in_training: true
  low_level_end_idx: 16
optimizer:
  name: adamw
  params:
    learning_rate: 1.0e-05
    scale_lr: false
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0.0
    epsilon: 1.0e-08
lr_scheduler:
  scheduler: cosine
  params:
    learning_rate: ${optimizer.params.learning_rate}
    warmup_steps: 0
    min_lr_scale: 1.0
logging:
  backend: wandb
  log_dir: tensorboard_logs
  log_interval: 5
  eval_interval: 100
config: configs/sft_llada_recursive.yaml
