experiment:
    project: "sft_llada_recursive3"
    num_node: 1

debug: False

model:
    pretrained_model: "/mnt/shared-storage-user/formalverification-shared/gaoxin/models/LLaDA-8B-Instruct"
    optimized_name: "optimized_recursive"

dataset:
    train_data: "gsm8k_aug_nl"
    validation_data: "gsm8k_aug_nl"

training:
    gradient_checkpointing_enable: False  # Enable to save memory
    gradient_accumulation_steps: 4  # Increase to maintain effective batch size
    batch_size_lm: 16  # Reduce to 1 to save memory
    mixed_precision: "bf16"
    enable_tf32: False
    seed: 42
    num_train_epochs: 25
    max_grad_norm: 1

    # Masking strategy
    method: "random_masking"
    lower_p: 0.1
    upper_p: 0.9
    block_size: 32
    mask_times_per_sample: 1
    post_num: 8
    max_gen_length: 512
    max_prompt_len: 784
    
    # Latent Recursive parameters
    use_latent_recursive: True
    R: 2 # latent recursive steps (before every unmask steps)
    recursive_in_training: True
    low_level_end_idx: 16

optimizer:
    name: adamw
    params:
        learning_rate: 1e-5
        scale_lr: False
        beta1: 0.9
        beta2: 0.999
        weight_decay: 0.0
        epsilon: 1e-8

lr_scheduler:
    scheduler: "cosine"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 0
        min_lr_scale: 1.0

# Logging configuration
logging:
    backend: "wandb"   # 可选: "wandb" | "tensorboard" | "none"
    log_dir: "tensorboard_logs"
    log_interval: 5